version: '3.8'

services:
  api:
    container_name: forprosjekt-api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env

  web:
    container_name: forprosjekt-web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: always
    ports:
      - 4000:4000

  hivemq:
    image: hivemq/hivemq-ce:2022.1
    ports:
      - 1883:1883

  postgres:
    container_name: 'postgres'
    image: postgres:13
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    expose:
      - ${DATABASE_PORT}/tcp
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DATABASE}
    command: -p ${DATABASE_PORT}
    volumes:
      - ./database/data:/var/lib/postgresql/data # persist data
      - ./database/backups:/usr/src/backups # store backups
